/**
 * Chart Card Schema
 * 
 * JSON Schema definition with x-ui-hints for LCARdS Chart Card.
 * Generated by tools/create-editor.js on 2025-12-30
 * 
 * Use tools/schema-editor.html for visual editing.
 * 
 * @see doc/editor/schema-ui-hints.md
 */

export const chartSchema = {
    "type": "object",
    "required": [
        "type"
    ],
    "properties": {
        "type": {
            "type": "string",
            "const": "custom:lcards-chart",
            "x-ui-hints": {
                "hidden": true
            }
        },
        "entity": {
            "type": "string",
            "format": "entity",
            "x-ui-hints": {
                "label": "Entity",
                "helper": "Select the primary entity for this card",
                "selector": {
                    "entity": {}
                }
            }
        },
        "name": {
            "type": "string",
            "x-ui-hints": {
                "label": "Name",
                "helper": "Display name for the card (optional)",
                "selector": {
                    "text": {}
                }
            }
        },
        "style": {
            "type": "object",
            "x-ui-hints": {
                "label": "Style Configuration"
            },
            "properties": {
                "background": {
                    "type": "object",
                    "properties": {
                        "color": {
                            "type": "string",
                            "format": "color",
                            "x-ui-hints": {
                                "label": "Background Color",
                                "helper": "Card background color",
                                "selector": {
                                    "ui_color": {}
                                }
                            }
                        }
                    }
                },
                "border": {
                    "type": "object",
                    "properties": {
                        "radius": {
                            "oneOf": [
                                {
                                    "type": "number",
                                    "title": "Pixels",
                                    "minimum": 0,
                                    "maximum": 50
                                },
                                {
                                    "type": "string",
                                    "title": "Theme Token",
                                    "pattern": "^\\{theme:.*\\}$"
                                }
                            ],
                            "x-ui-hints": {
                                "label": "Border Radius",
                                "helper": "Corner rounding in pixels or theme token",
                                "selector": {
                                    "choose": {
                                        "choices": {
                                            "pixels": {
                                                "selector": {
                                                    "number": {
                                                        "mode": "slider",
                                                        "min": 0,
                                                        "max": 50,
                                                        "step": 1,
                                                        "unit_of_measurement": "px"
                                                    }
                                                }
                                            },
                                            "theme": {
                                                "selector": {
                                                    "text": {
                                                        "placeholder": "{theme:border.radius}"
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                },
                "padding": {
                    "oneOf": [
                        {
                            "type": "number",
                            "title": "Uniform",
                            "minimum": 0,
                            "maximum": 100
                        },
                        {
                            "type": "object",
                            "title": "Per Side",
                            "properties": {
                                "top": {
                                    "type": "number",
                                    "minimum": 0
                                },
                                "right": {
                                    "type": "number",
                                    "minimum": 0
                                },
                                "bottom": {
                                    "type": "number",
                                    "minimum": 0
                                },
                                "left": {
                                    "type": "number",
                                    "minimum": 0
                                }
                            }
                        }
                    ],
                    "x-ui-hints": {
                        "label": "Padding",
                        "helper": "Internal spacing",
                        "selector": {
                            "choose": {
                                "choices": {
                                    "uniform": {
                                        "selector": {
                                            "number": {
                                                "mode": "slider",
                                                "min": 0,
                                                "max": 100,
                                                "unit_of_measurement": "px"
                                            }
                                        }
                                    },
                                    "per_side": {
                                        "selector": {
                                            "object": {}
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        },
        "tap_action": {
            "type": "object",
            "format": "action",
            "x-ui-hints": {
                "label": "Tap Action",
                "helper": "Action to perform when tapped",
                "selector": {
                    "ui_action": {}
                }
            }
        },
        "hold_action": {
            "type": "object",
            "format": "action",
            "x-ui-hints": {
                "label": "Hold Action",
                "helper": "Action to perform on long press",
                "selector": {
                    "ui_action": {}
                }
            }
        }
    }
};

// TODO: Add chart-specific properties here
// Use tools/schema-editor.html for visual editing
